# Test the Service Home Endpoint
GET http://localhost:8081/home

###

# Test the Service Send SMS Endpoint
POST http://localhost:8081/sendsms
Content-Type: application/json

{
  "from": "Majid",
  "to": "+123456789",
  "body": "Direct test message to Final Service"
}

###

# Test the Service Get Status Endpoint
GET http://localhost:8081/getstatus?message-id=<message-id-placeholder>
