@no-ssl-verify

###
POST https://localhost:8443/v1/api/sms/send
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDcwNDk1MzUsInJvbGUiOiJhZG1pbiIsInVzZXIiOiJhZG1pbiJ9.oQiP7pbfi5i6b3lhsEBsh9t9Krx13texQW2Z9F2IyQg
Content-Type: application/json

{
  "senders": ["982000123"],
  "receivers": ["989121234567"],
  "text": ["this is a long message1. this is a long message2. this is a long message3. this is a long message4. this is a long message5. this is a long message6. this is a long message7."],
  "track_id": ["10171"]
}

###
POST https://localhost:8443/v1/api/sms/send
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY1OTg5MDcsInJvbGUiOiJhZG1pbiIsInVzZXIiOiJhZG1pbiJ9.Ay9rPkx5ka6aBFKGGZef7B83fyCEfWx48caWOO-4FAQ
Content-Type: application/json

{
  "sender": ["982000123"],
  "receivers": ["989121234567", "989121234568"],
  "text": ["this is a long message1. this is a long message2. this is a long message3. this is a long message4. this is a long message5. this is a long message6. this is a long message7."],
  "track_id": ["1004", "1005"]
}


###
GET https://localhost:8443/v1/api/sms/track?track_id=10171
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDcwNDk1MzUsInJvbGUiOiJhZG1pbiIsInVzZXIiOiJhZG1pbiJ9.oQiP7pbfi5i6b3lhsEBsh9t9Krx13texQW2Z9F2IyQg


###
GET https://localhost:8443/v1/api/sms/track?req_id=4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDcwNDk1MzUsInJvbGUiOiJhZG1pbiIsInVzZXIiOiJhZG1pbiJ9.oQiP7pbfi5i6b3lhsEBsh9t9Krx13texQW2Z9F2IyQg
