### Register Admin User
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "admin",
  "password": "password",
  "role": "admin"
}

### Register a New User
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "demo1",
  "password": "demo123",
  "role": "guest"
}

### Delete a user
DELETE http://localhost:8080/user/demo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDUxMzEwNzIsInJvbGUiOiJhZG1pbiIsInN1YiI6ImFkbWluIn0.QIVY13wgBu93eYIh1RXPFrKlG2H3tN9cxZXpZyiceSg

### Test the Auth Service Login Endpoint (Generate JWT Token)
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

### Test the Auth Service Login Endpoint (Generate JWT Token)
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "demo1",
  "password": "demo123"
}

### Test the Auth Service Home Endpoint (Protected)
GET http://localhost:8080/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3ODg5MzcsInJvbGUiOiJhZG1pbiIsInN1YiI6ImFkbWluIn0.16Ke962JfGhNX17UdIZa8nH1Jbg3XutR52dvmiAsCAE

### Test the Auth Service Send SMS Endpoint (Protected)
POST http://localhost:8080/sendsms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDUxMzE2MjcsInJvbGUiOiJndWVzdCIsInN1YiI6ImRlbW8xIn0.AwZ297d4LoCZlg4XdQKY3T9GEOWnkKf_CXkDmq6O6J4
Content-Type: application/json

{
  "from": "Majid",
  "to": "+123456789",
  "body": "Hello, this is a test message!"
}

### Test the Auth Service Get Status Endpoint (Protected)
GET http://localhost:8080/getstatus?message-id=4b17ae82-4d72-43a8-abab-99cb55c5d86f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3ODg5MzcsInJvbGUiOiJhZG1pbiIsInN1YiI6ImFkbWluIn0.16Ke962JfGhNX17UdIZa8nH1Jbg3XutR52dvmiAsCAE

### Update User Role (Admin Only)
PUT http://localhost:8080/user/demo/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3ODg5MzcsInJvbGUiOiJhZG1pbiIsInN1YiI6ImFkbWluIn0.16Ke962JfGhNX17UdIZa8nH1Jbg3XutR52dvmiAsCAE

{
  "role": "editor"
}

### Create a New Role (Admin Only)
POST http://localhost:8080/roles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ4OTYwNTEsInJvbGUiOiJhZG1pbiIsInN1YiI6ImFkbWluIn0.aC5tX1j_tegUmYxD7V52-zLYIVbHpMtxofGBh2TTFhQ

{
  "name": "editor",
  "description": "Can edit content"
}

### Test SMS Charging
POST http://localhost:8080/sms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDUxMzE2MjcsInJvbGUiOiJndWVzdCIsInN1YiI6ImRlbW8xIn0.AwZ297d4LoCZlg4XdQKY3T9GEOWnkKf_CXkDmq6O6J4

### Define an Accounting Rule (Admin Only)
POST http://localhost:8080/accounting_rules
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDUxMzE1ODMsInJvbGUiOiJhZG1pbiIsInN1YiI6ImFkbWluIn0.EJLxsIFx04M9NcnukElH2WSd3LnV1rV8mSaN_kzaibI

{
  "endpoint": "/sendsms",
  "charge": 5
}
